config/routes.rb
require 'sidekiq/web'
Pingpong::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	root to: "users#index"

  resources :matches do
    member do
      get :play
    end

    collection do
      get "pending", to: "matches#pending_matches"
    end
  end

  as :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "devise/sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end


  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/leaderboard" => "users#index", as: :leaderboard

  resources :tournaments do
    resources :matches do
      member do
        get :play
      end

      collection do
        get "pending", to: "matches#pending_matches"
      end
    end
  end
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	TYPE_CHOICES = {
		'Round Robin' 				=> 'RR',
		'Single Elimination' 	=> 'SE',
		'Double Elimination' 	=> 'DE',
		'Winner Stays' 				=> 'WS'
	}


	validates_inclusion_of :tournament_type, in: TYPE_CHOICES.values, allow_nil: true

	has_many :matches
	has_many :tournament_users
	has_many :players, -> { distinct }, through: :tournament_users, source: :user

	accepts_nested_attributes_for :matches

	def long_type
		TYPE_CHOICES.invert[self.tournament_type]
	end

	def initalize
		self.num_players = self.players.count
	end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def show
  end

  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, info: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, info: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:tournament_type, :num_players)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.haml
= simple_form_for @tournament, :html => { :class => 'form-horizontal' } do |f|
  = f.input :tournament_type
  = f.input :num_players
  = f.fields_for :match do |m|
    - m.input :player1
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      tournaments_path, :class => 'btn'                            |

app/views/tournaments/edit.html.haml
- model_class = Tournament
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tournaments/index.html.haml
- model_class = Tournament
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:tournament_type)
      %th= model_class.human_attribute_name(:num_players)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @tournaments.each do |tournament|
      %tr
        %td= link_to tournament.id, tournament_path(tournament)
        %td= tournament.tournament_type
        %td= tournament.num_players
        %td= l tournament.created_at
        %td
          = link_to 'Edit', edit_tournament_path(tournament), class: 'btn btn-xs btn-primary'
          = link_to 'Delete', tournament_path(tournament), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
= link_to 'New', new_tournament_path, class: 'btn btn-primary'

app/views/tournaments/new.html.haml
- model_class = Tournament
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tournaments/show.html.haml
- model_class = Tournament
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:tournament_type)
      \:
  %dd= @tournament.long_type
  %dt
    %strong
      = model_class.human_attribute_name(:num_players)
      \:
  %dd= @tournament.num_players
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    tournaments_path, :class => 'btn'                        |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_tournament_path(@tournament), :class => 'btn'       |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    tournament_path(@tournament),                                                                                |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |