config/routes.rb
require 'sidekiq/web'
Pingpong::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	root to: "users#index"

  resources :matches do
    member do
      get :play
    end

    collection do
      get "pending", to: "matches#pending_matches"
    end
  end

  as :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "devise/sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end


  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/leaderboard" => "users#index", as: :leaderboard

  resources :tournaments do
    resources :matches do
      member do
        get :play
      end

      collection do
        get "pending", to: "matches#pending_matches"
      end
    end
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
	# score1 is player1's score and score2 is player2's score
  after_save :update_users_stats


  STATUS_CHOICES = {
   'Pending'      =>  'P',
   'In Progress'  => 'IP',
   'Complete'     =>  'C',
   'Canceled'     =>  'X'
  }

  belongs_to :player1, class_name: "User", foreign_key: :player1_id
  belongs_to :player2, class_name: "User", foreign_key: :player2_id
  belongs_to :tournament

  validates :player1, presence: true
  validates :player2, presence: true
  validate :cannot_play_self

  validates_inclusion_of :status, in: STATUS_CHOICES.values, allow_nil: true


  def winner
  	if self.status == 'C'
	    self.score1 > self.score2 ? self.player1 : self.player2
  	end
  end

  def players
    [self.player1, self.player2]
  end

  def to_s
    "#{self.player1} vs. #{self.player2}"
  end

  def long_status
    STATUS_CHOICES.invert[self.status]
  end


  private
  def cannot_play_self
    errors[:base] << 'You cannot play against yourself. <strong>Get a life.</strong>' if self.player1_id == self.player2_id
  end

  def update_users_stats
    if status == 'C'
      player1.update_stats
      player2.update_stats
      UserStatsWorker.new.perform
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :pending_matches]
  before_action :set_tournament
  before_action :set_match, only: [:show, :edit, :update, :destroy, :play]

  def index
    params[:page] ||= 1
    unless @tournament
      @matches = Match.includes(:player1, :player2).order('id desc').paginate(:page => params[:page], :per_page => 10)
    else
      @matches = @tournament.matches.includes(:player1, :player2).order('id desc').paginate(:page => params[:page], :per_page => 10)
    end
  end

  def pending_matches
    params[:page] ||= 1
    unless @tournament
      @matches = Match.where(status: ['P', 'IP']).order('id desc').paginate(:page => params[:page], :per_page => 10)
    else
      @matches = @tournament.matches.where(status: ['P', 'IP']).order('id desc').paginate(:page => params[:page], :per_page => 10)
    end
    respond_to do |format|
      format.html { render template: 'matches/index.html.haml' }
    end
  end

  def new
    unless @tournament
      @match = Match.new
    else
      @match = @tournament.matches.new
    end

  end

  def edit
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to matches_url
    else
      flash.now[:danger] = object_errors_flash( @match )
      render :new
    end
  end

  def update

    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, info: 'Match was successfully updated.' }
        format.js { head :no_content }
      else
        format.html do
          flash.now[:danger] = object_errors_flash( @match )
          render :edit
        end
        format.js { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  def play
    if ['IP', 'P'].include? @match.status
      @match.update_attribute :status, 'IP'
      @match
    else
      redirect_to matches_url
    end
  end


  private
    def set_match
      @match = Match.find(params[:id])
    end

    def match_params
      params.require(:match).permit(:status, :player1_id, :player2_id, :score1, :score2)
    end

    def set_tournament
      @tournament = Tournament.find(params[:tournament_id]) if params[:tournament_id]
    end

end

app/helpers/matches_helper.rb
module MatchesHelper

  def player_input( f, player )
    if params[:action] == 'edit'
      f.input player, as: :static
    else
      f.association player
    end
  end

end

app/views/matches/_form.html.haml
.col-sm-6
  .panel.panel-primary
    .panel-heading
      %h3.panel-title= "#{params[:action].titleize} Match"
    .panel-body
      = simple_form_for @match do |f|
        .col-sm-12
          /= f.input :tournament_id
          = f.input :status, collection: Match::STATUS_CHOICES

        .col-sm-6
          = player_input( f, :player1 )
          = f.input :score1

        .col-sm-6
          = player_input( f, :player2 )
          = f.input :score2

        .form-group.text-center
          = f.button :submit, class: 'btn btn-primary'
          = link_to 'Cancel', matches_path, class: 'btn btn-default'

app/views/matches/edit.html.haml
.page-header
  %h1= "#{@match.player1} vs. #{@match.player2}"
= render 'form'

app/views/matches/index.html.haml
.page-header
  %h1
    Matches
    .pull-right
      = link_to 'New Match', new_match_path, class: 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th Status
      %th Player 1
      %th Player 1 Score
      %th Player 2
      %th Player 2 Score
      %th Winner
      %th Actions
  %tbody
    - @matches.each do |match|
      %tr
        %td= Match::STATUS_CHOICES.invert[match.status]
        %td
          %span.rank
            = match.player1.rank
          = match.player1
        %td= match.score1
        %td
          %span.rank
            = match.player2.rank
          = match.player2
        %td= match.score2
        %td
          = match.winner
        %td
          - if ['P', 'IP'].include? match.status
            = link_to 'Play', play_match_path(match), class: 'btn btn-info btn-xs'
          - if match.status == 'P' || edit?
            = link_to 'Edit', edit_match_path(match), class: 'btn btn-warning btn-xs'
            - if edit?
              = link_to 'Delete', match_path(match), method: :delete, confirm: 'Are you sure?', class: 'btn btn-xs btn-danger'
= will_paginate @matches

app/views/matches/new.html.haml
.page-header
  %h1 New Match
= render partial: 'form'

app/views/matches/play.html.haml
.row{style: 'padding-top: 25px;'}
  .col-sm-10.text-center
    .score#p1-score.text-center
      %span.points= @match.score1
      .name= @match.player1.first_name
    .hidden-xs.separator -
    .score#p2-score.text-center
      %span.points= @match.score2
      .name= @match.player2.first_name
    = button_tag 'End Game', class: 'btn btn-large btn-black', id: 'end-game', style: 'margin: 45px auto 0; display: block;'

#form-container.hidden
  = simple_form_for @match, remote: true do |f|
    = f.input :status, collection: Match::STATUS_CHOICES
    = f.association :player1
    = f.input :score1
    = f.association :player2
    = f.input :score2