config/routes.rb
require 'sidekiq/web'
Pingpong::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	root to: "users#index"

  resources :matches do
    member do
      get :play
    end

    collection do
      get "pending", to: "matches#pending_matches"
    end
  end

  as :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "devise/sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end


  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/leaderboard" => "users#index", as: :leaderboard

  resources :tournaments do
    resources :matches do
      member do
        get :play
      end

      collection do
        get "pending", to: "matches#pending_matches"
      end
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}/
    %meta{:content => 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible'}/
    %meta{:content => 'width=device-width, initial-scale=1.0', :name => 'viewport'}/
    %title= content_for?(:title) ? yield(:title) : 'Pingpong'
    = csrf_meta_tags

    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'ping-pong.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'ping-pong.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'ping-pong.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'ping-pong.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle{ data: {target: '.navbar-collapse', toggle: 'collapse'} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Ping Pong', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.dropdown
                %a#user-img.dropdown-toggle{ data: {toggle: 'dropdown'} }
                  = image_tag( current_user.image, class: 'img-rounded' )
                  = icon('caret-down')
                %ul.dropdown-menu
                  %li= link_to 'Profile', edit_user_registration_path
                  %li= link_to 'Logout', logout_path
            - else
              = link_to icon('google-plus-square', 'Sign in with Google'), user_omniauth_authorize_path(:google_oauth2), class: 'btn btn-blk btn-social btn-google-plus navbar-btn'

    .container-fluid
      .row
        .col-md-3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Quick Links
              %li= link_to 'Matches', matches_path
              %li= link_to 'Pending Matches', pending_matches_path
              %li= link_to 'Leaderboard', leaderboard_path
              %li= link_to 'Tournaments', tournaments_path


        .col-md-9
          - flash.each do |klass, msg|
            .alert.alert-dismissible{ class: "alert-#{klass}"}
              %button.close{ data: {dismiss: 'alert'} } &times;
              = msg

          = yield

      %footer